name: Clang-Tidy

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  industrial_ci:
    name: ClangTidy
    runs-on: ubuntu-22.04
    env:
      CI_NAME: Clang-Tidy
      OS_NAME: ubuntu
      OS_CODE_NAME: jammy
      ROS_DISTRO: humble
      ROS_REPO: main
      ADDITIONAL_DEBS: clang-tidy
      UPSTREAM_WORKSPACE: 'dependencies.repos'
      ROSDEP_SKIP_KEYS: "catkin taskflow orocos_kdl fcl"
      DOCKER_IMAGE: "ros:humble"
      NOT_TEST_BUILD: true
      CCACHE_DIR: "/home/runner/work/tesseract_ros/tesseract_ros/Clang-Tidy/.ccache"
      UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"
      TARGET_CMAKE_ARGS: "-DTESSERACT_ENABLE_CLANG_TIDY=ON -DTESSERACT_ENABLE_TESTING=ON"
    steps:
      - uses: actions/checkout@v1

      - name: Free Disk Space
        continue-on-error: true
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        continue-on-error: true
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.CI_NAME }}/.ccache
          key: ${{ env.CI_NAME }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ env.CI_NAME }}-ccache-

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{env}}
