name: Focal-Build

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * 6'
  workflow_dispatch:

jobs:
  industrial_ci:
    name: Foxy
    runs-on: ubuntu-20.04
    env:
      CI_NAME: Focal-Build
      OS_NAME: ubuntu
      OS_CODE_NAME: focal
      ROS_DISTRO: foxy
      ROS_REPO: main
      BEFORE_INIT: './.add-gazebo-ppa'
      UPSTREAM_WORKSPACE: 'dependencies.repos'
      ROSDEP_SKIP_KEYS: "catkin taskflow fcl gz-common5 gz-math7"
      ADDITIONAL_DEBS: "libgz-common5-dev libgz-math7-dev"
      DOCKER_IMAGE: "ros:foxy"
      PARALLEL_TESTS: false
      NOT_TEST_BUILD: true
      BEFORE_RUN_TARGET_TEST_EMBED: "source /root/target_ws/install/local_setup.bash"
      CCACHE_DIR: "/home/runner/work/tesseract_ros2/tesseract_ros2/Focal-Build/.ccache"
      UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release"
      TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"
    steps:
      - uses: actions/checkout@v1

      - name: Free Disk Space
        continue-on-error: true
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        continue-on-error: true
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.CI_NAME }}/.ccache
          key: ${{ env.CI_NAME }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ env.CI_NAME }}-ccache-

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{env}}
