name: Focal-Build

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * 6'

jobs:
  industrial_ci:
    name: Foxy
    runs-on: ubuntu-latest
    env:
      CI_NAME: Focal-Build
      OS_NAME: ubuntu
      OS_CODE_NAME: focal
      ROS_DISTRO: foxy
      ROS_REPO: main
      UPSTREAM_WORKSPACE: 'dependencies.repos'
      # ROSDEP_SKIP_KEYS: "bullet bullet-extras ros_industrial_cmake_boilerplate fcl iwyu taskflow"
      ROSDEP_SKIP_KEYS: "catkin taskflow"
      DOCKER_IMAGE: "ros:foxy"
      PARALLEL_TESTS: false
      NOT_TEST_BUILD: true
      CCACHE_DIR: "/home/runner/work/tesseract_ros/tesseract_ros/Focal-Build/.ccache"
      UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release"
      TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"
    steps:
      - uses: actions/checkout@v1

      - name: Free Disk Space
        continue-on-error: true
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        continue-on-error: true
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.CI_NAME }}/.ccache
          key: ${{ env.CI_NAME }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ env.CI_NAME }}-ccache-

      - name: Install taskflow
        working-directory: /home/runner
        env:
          TASKFLOW_VERSION: v3.3.0
        run: |
          git clone https://github.com/taskflow/taskflow.git
          git -C taskflow checkout $TASKFLOW_VERSION
          mkdir taskflow-build
          cmake -S taskflow -B taskflow-build -DCMAKE_INSTALL_PREFIX=/usr -DTF_BUILD_TESTS=OFF -DTF_BUILD_EXAMPLES=OFF
          sudo make -C taskflow-build/ install
          rm -rf taskflow/ taskflow-build/

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{env}}
